name: Apply Patch

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  patch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Apply patch
        run: |
          patch -p1 < update.patch

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Index.html
          git commit -m "Automated patch applied" || echo "No changes to commit"

      - name: Pull remote changes (rebase)
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git pull --rebase origin main

      - name: Push changes using PAT
        run: |
          git push origin HEAD:main
